Change pass page 95%
acm-uic/Addict-Frontend pull request #53
Opened 2022-06-03 01:40 UTC by Ajknight121

2022-06-03 01:46 UTC, Ajknight121 commented
So the remaining issue is the Password input does not show a default text of "password" that is visible to the user. I also was not able to figure out how to make the background image fill the page while not activating the scroll bar.

2022-06-03 02:03 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <label><h2>Username:</h2></label>
Remove the labels they should be inside the textbooks

2022-06-03 02:04 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <input type="text" defaultValue={"Username"} onChange = {event => username = event.target.value}/><br/>
Change the defaultValue param to placeholder without the javascript injection

2022-06-03 02:05 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <label><h2>New password:</h2></label>
See above

2022-06-03 02:05 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <input type="password" defaultValue={"password"} onChange = {event => newpass = event.target.value}/><br/>
See above

2022-06-03 02:05 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
>      let username: string = ""
Finish the functionality here

2022-06-03 02:07 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <div className="button" onClick={ChangePass}>Submit</div>
Change to ChangePassword

2022-06-03 02:21 UTC, ChristianBingman requested changes
Make sure that changes on a branch directly relate to the stated changes

- [x] Fix the issues with the textbox sizes
- [ ] Fix placeholder changes
- [ ] Remove the labels

2022-06-10 01:57 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <input type="text" placeholder={"Username"} onChange = {event => username = event.target.value}/><br/>
This should be "New Password"

2022-06-10 01:57 UTC, ChristianBingman commented on src/pages/ChangePassword.tsx
> +                <input type="password" placeholder={"New password"} onChange = {event => newpass = event.target.value}/><br/>
This should be "New Password Confirm"

2022-06-10 01:58 UTC, ChristianBingman requested changes
- [ ] Change the placeholder to what is commented

2022-06-10 02:44 UTC, merged